version: '3.8'

services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=Europe/Moscow
      - VALIDATION=http
      - SUBDOMAINS=lubimovka,test-lubimovka
      - CERTPROVIDER=zerossl
      - ONLY_SUBDOMAINS=true
    env_file:
      - .env-dev
    networks:
      - swag_network
    volumes:
      - ./swag_config/:/config/
      - ./swag/swag_nginx.conf:/config/nginx/site-confs/default
      - static_value:/config/static/
      - media_value:/config/media/
      - static_value_test:/config/test/static/
      - media_value_test:/config/test/media/
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

networks:
  swag_network:
    external: true

volumes:
  static_value:
  media_value:
  static_value_test:
  media_value_test:
