# Generated by Django 3.2.7 on 2021-10-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_pages', '0003_alter_content_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
