# Generated by Django 3.2.7 on 2021-10-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_pages', '0004_alter_content_object_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='content',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Position'),
            preserve_default=False,
        ),
    ]
