# Generated by Django 3.2.7 on 2021-10-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_pages', '0005_auto_20211004_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderedimage',
            options={'ordering': ['position']},
        ),
        migrations.RemoveField(
            model_name='content',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderedimage',
            name='order',
        ),
        migrations.AddField(
            model_name='orderedimage',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Position'),
            preserve_default=False,
        ),
    ]
